package com.margelo.nitro.com.mediatoolkit

import androidx.media3.common.util.UnstableApi
import com.margelo.nitro.NitroModules
import com.margelo.nitro.com.mediatoolkit.CompressImageOptions
import com.margelo.nitro.com.mediatoolkit.CompressVideoOptions
import com.margelo.nitro.com.mediatoolkit.CropOptions
import com.margelo.nitro.com.mediatoolkit.HybridMediaToolkitSpec
import com.margelo.nitro.com.mediatoolkit.MediaResult
import com.margelo.nitro.com.mediatoolkit.TrimOptions
import com.margelo.nitro.com.mediatoolkit.FlipOptions
import com.margelo.nitro.com.mediatoolkit.ProcessImageOptions
import com.margelo.nitro.com.mediatoolkit.ProcessVideoOptions
import com.margelo.nitro.com.mediatoolkit.RotateOptions
import com.margelo.nitro.com.mediatoolkit.ThumbnailOptions
import com.margelo.nitro.com.mediatoolkit.ThumbnailResult
import com.margelo.nitro.com.mediatoolkit.TrimAndCropOptions
import com.margelo.nitro.com.mediatoolkit.VideoCropOptions
import com.margelo.nitro.core.Promise
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob

/**
 * Nitro HybridObject implementation for MediaToolkit on Android.
 * Extends HybridMediaToolkitSpec generated by nitrogen.
 * ImageProcessor and VideoProcessor are kept unchanged — only this glue layer is rewritten.
 */
@UnstableApi
class HybridMediaToolkit : HybridMediaToolkitSpec() {

  private val scope = CoroutineScope(SupervisorJob() + Dispatchers.IO)

  private val ctx get() = requireNotNull(NitroModules.applicationContext) {
    "ReactApplicationContext not available — is NitroModules installed?"
  }

  // ─── Image ────────────────────────────────────────────────────────────────

  override fun cropImage(uri: String, options: CropOptions): Promise<MediaResult> {
    return Promise.async(scope) {
      val raw = ImageProcessor.cropImage(
        uri,
        options.x,
        options.y,
        options.width,
        options.height,
        options.outputPath
      )
      raw.toMediaResult()
    }
  }

  override fun compressImage(uri: String, options: CompressImageOptions): Promise<MediaResult> {
    return Promise.async(scope) {
      val raw = ImageProcessor.compressImage(
        uri,
        (options.quality ?: 80.0).toInt(),
        (options.maxWidth ?: 0.0).toInt(),
        (options.maxHeight ?: 0.0).toInt(),
        options.format ?: "jpeg",
        options.outputPath
      )
      raw.toMediaResult()
    }
  }

  override fun flipImage(uri: String, options: FlipOptions): Promise<MediaResult> {
    return Promise.async(scope) {
      val raw = ImageProcessor.flipImage(
        uri,
        options.direction,
        options.outputPath
      )
      raw.toMediaResult()
    }
  }

  override fun rotateImage(uri: String, options: RotateOptions): Promise<MediaResult> {
    return Promise.async(scope) {
      val raw = ImageProcessor.rotateImage(
        uri,
        options.degrees,
        options.outputPath
      )
      raw.toMediaResult()
    }
  }

  override fun processImage(uri: String, options: ProcessImageOptions): Promise<MediaResult> {
    return Promise.async(scope) {
      val raw = ImageProcessor.processImage(
        uri,
        options.cropX ?: 0.0,
        options.cropY ?: 0.0,
        options.cropWidth ?: 0.0,
        options.cropHeight ?: 0.0,
        options.flip,
        options.rotation ?: 0.0,
        options.outputPath
      )
      raw.toMediaResult()
    }
  }

  // ─── Video ────────────────────────────────────────────────────────────────

  override fun trimVideo(uri: String, options: TrimOptions): Promise<MediaResult> {
    return Promise.async(scope) {
      val raw = VideoProcessor.trimVideo(
        ctx,
        uri,
        options.startTime.toLong(),
        options.endTime.toLong(),
        options.outputPath
      ) { /* progress ignored — Nitro doesn't use EventEmitter */ }
      raw.toMediaResult()
    }
  }

  override fun cropVideo(uri: String, options: VideoCropOptions): Promise<MediaResult> {
    return Promise.async(scope) {
      val raw = VideoProcessor.cropVideo(
        ctx,
        uri,
        options.x.toFloat(),
        options.y.toFloat(),
        options.width.toFloat(),
        options.height.toFloat(),
        options.outputPath
      ) { /* progress ignored */ }
      raw.toMediaResult()
    }
  }

  override fun compressVideo(uri: String, options: CompressVideoOptions): Promise<MediaResult> {
    return Promise.async(scope) {
      val raw = VideoProcessor.compressVideo(
        ctx,
        uri,
        options.quality ?: "medium",
        (options.bitrate ?: 0.0).toInt(),    // 0 = use quality preset (mirrors iOS behaviour)
        options.targetSizeInMB ?: 0.0,
        options.minResolution ?: 720.0,
        (options.width ?: 0.0).toInt(),
        options.muteAudio ?: false,
        options.outputPath
      ) { /* progress ignored */ }
      raw.toMediaResult()
    }
  }

  override fun trimAndCropVideo(uri: String, options: TrimAndCropOptions): Promise<MediaResult> {
    return Promise.async(scope) {
      val raw = VideoProcessor.trimAndCropVideo(
        ctx,
        uri,
        options.startTime.toLong(),
        options.endTime.toLong(),
        options.x.toFloat(),
        options.y.toFloat(),
        options.width.toFloat(),
        options.height.toFloat(),
        options.outputPath
      ) { /* progress ignored */ }
      raw.toMediaResult()
    }
  }

  override fun flipVideo(uri: String, options: FlipOptions): Promise<MediaResult> {
    return Promise.async(scope) {
      val raw = VideoProcessor.flipVideo(
        ctx,
        uri,
        options.direction,
        options.outputPath
      ) { /* progress ignored */ }
      raw.toMediaResult()
    }
  }

  override fun rotateVideo(uri: String, options: RotateOptions): Promise<MediaResult> {
    return Promise.async(scope) {
      val raw = VideoProcessor.rotateVideo(
        ctx,
        uri,
        options.degrees,
        options.outputPath
      ) { /* progress ignored */ }
      raw.toMediaResult()
    }
  }

  override fun processVideo(uri: String, options: ProcessVideoOptions): Promise<MediaResult> {
    return Promise.async(scope) {
      val raw = VideoProcessor.processVideo(
        ctx,
        uri,
        (options.startTime ?: 0.0).toLong(),
        (options.endTime ?: 0.0).toLong(),
        (options.cropX ?: 0.0).toFloat(),
        (options.cropY ?: 0.0).toFloat(),
        (options.cropWidth ?: 0.0).toFloat(),
        (options.cropHeight ?: 0.0).toFloat(),
        options.flip,
        options.rotation ?: 0.0,
        options.outputPath
      ) { /* progress ignored */ }
      raw.toMediaResult()
    }
  }

  override fun getThumbnail(uri: String, options: ThumbnailOptions?): Promise<ThumbnailResult> {
    return Promise.async(scope) {
      val timeMs   = options?.timeMs?.toLong() ?: 0L
      val quality  = options?.quality?.toInt() ?: 80
      val maxWidth = options?.maxWidth?.toInt() ?: 0
      val raw = VideoProcessor.getThumbnail(ctx, uri, timeMs, quality, maxWidth, options?.outputPath)
      ThumbnailResult(
        uri      = raw["uri"]      as? String ?: "",
        size     = (raw["size"]     as? Number)?.toDouble() ?: 0.0,
        width    = (raw["width"]    as? Number)?.toDouble() ?: 0.0,
        height   = (raw["height"]   as? Number)?.toDouble() ?: 0.0,
        duration = (raw["duration"] as? Number)?.toDouble() ?: 0.0
      )
    }
  }
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

private fun Map<String, Any>.toMediaResult(): MediaResult {
  return MediaResult(
    uri      = this["uri"]      as? String ?: "",
    size     = (this["size"]    as? Number)?.toDouble() ?: 0.0,
    width    = (this["width"]   as? Number)?.toDouble() ?: 0.0,
    height   = (this["height"]  as? Number)?.toDouble() ?: 0.0,
    duration = (this["duration"]as? Number)?.toDouble() ?: 0.0,
    mime     = this["mime"]     as? String ?: ""
  )
}
